### PR TITLE
Development

### PR DESCRIPTION
**Pull request by RamseyNjire**
Here is my attempt at cloning the old 2014 Apple site. I used CSS grid extensively for the layout and linear and radial gradients for the backgrounds on the navbar. I hope you like it!

### CODE REVIEW

**Comment by majovanilla** [comment]
Project under review by Maria Reyes

**Comment by majovanilla** [comment]
Hey @RamseyNjire , 👋

## Good job on this project! 👍

- I liked your Readme file (see optional changes at the end)
- Good Pull Request Message (see optional changes at the end)

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some errors and warnings. Please fix them.
Screenshot from 2020-02-24 19-36-03


**Your page should look closer to the original one. I will give you some tips to make this happen** :smile: 

 - Check the size of the navbar in the original page. It shouldn't take all the width of the background image.
Your page:
Screenshot from 2020-02-24 19-41-07

Original page:
Screenshot from 2020-02-24 19-40-59

- You are using semantic HTML for the page. That's great! :+1:  Just keep in mind that the general order of your HTML should be: nav, then main, then footer. Right now you have the nav inside the main section.

- The apple logo is not showing on the navbar. Please check you linked it correctly.

- The navbar elements should also be links instead of buttons. 

- Check the position of the main background image. Your page shows too much sky, causing all the elements to be pushed down and adding a vertical scroll that the original doesn't have. If you play with the position of the background shorthand, you can achieve the same look. 

- Related to the previous one: the whole page should fit in vertically. There is no need for a scroll.

- Check the 4 images on the bottom. They should occupy the same width as the main background. Yours are overflowing to the sides.

- On the same bottom images: play with the background shorthand to fill all the available space. If you see your images, they tend to repeat themselves inside the container.

- The four images should be links, right now they are sections. There is no need to include the link address, just use the proper tag.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Change the first paragraph of your Readme file so it appears before the screenshot of the project. Also, make it more readable (perhaps use 2 or 3 small paragraphs)

- Use your own screenshot, not from the original page. That way you don't mislead people.

- I recommend you to use lists (ul tag) to create navbars, it is so much easier to position them later using flex (horizontally or vertically).

- Check this [resource](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) about the correct use of buttons. Spoiler alert: you should use them to submit a form.

**Please, make all REQUIRED changes and submit your request again! 😀**

## Project Status: Changes required :warning: 


If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by RamseyNjire** [comment]
Hey @majovanilla !

I did the changes you recommended! I changed the <nav> into a <ul>. I got the background images to stop repeating, and I fitted everything into the screen without having to scroll. I also added anchor tags in the bottom sections. My standup team also added a few comments about class names so I made those less specific. Also edited the README.md file

Just one point: the screenshot was actually my own page and not the original, so I wasn't trying to mislead. If you look at the screenshot, you'll see that in the url bar it says 127.0.0.1:5500, which is my local port. 😄  

Thanks for all the helpful comments. I really hope you like the work now and I'm looking forward to further feedback! 😄

**Comment by lekegitrepo** [comment]
This PR is under Review by: [TSE] Temitayo Adeleke

**Comment by lekegitrepo** [comment]
## Hi @RamseyNjire, well done 👍 
You have made most of the required changes stipulated by the previous reviewer but there are still some changes you have not met:
1. **_This is very important: your project must pass all the linter tests_** before it can be approved

2. There is still a vertical scroll(as mention by the previous reviewer) on the page even if the browser window is maximized.
**_kindly make these changes and resubmit for review._**

**Reviewed by: _Temitayo Adeleke_**

If you have any doubt or question you can contact on slack.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Required Changes

**Comment by RamseyNjire** [comment]
Hi, @lekegitrepo! I made changes and passed the linter test. 

About the vertical scroll, I did change that and set the height of the site to the height of the browser window. The slight vertical scroll comes normally. Actually, the original Apple site also has a vertical scroll, especially if the magnification of the page is less than 100%. I did correct it, though. Hope it's okay now!

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :ok_hand:

**Comment by nikasulo** [comment]
# Nice job! @RamseyNjire 
You did good working on the stickler issue, also, I understand your comments about the scroll but if you consider looking more closely at the size of each elements, I'm sure you can stick the landing and get the page to present exactly like the original. That being said I did notice one issue/bug in your navigation. Please see below:

#### Missing logo
Please consider the screenshot below, your logo doesn't seem to show up, please look into this and make the appropriate change, afterwards, request another review! I wish you the very best and see you at the top! :rocket: 
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by RamseyNjire** [comment]
Thanks, @Oluwadamilareolusakin! Lemme see what I can do about the apple logo. It's an svg, so that might be the problem. Let me use a png file instead. Thanks for your kind words!

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @RamseyNjire       
#### Great Job so far, but there is one more thing required. 
### General
- [ ] The logo hasnt been fixed yet .


### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — APPROVED** [review]
Good work @RamseyNjire , Project Approved.
Go ahead and merge

**Comment by RamseyNjire** [comment]
Great! Thanks! Thank you everyone for the valuable feedback!

**Comment by RamseyNjire** [comment]
Oops! Closed the pull request by mistake. Will merge it now.

**Comment by RamseyNjire** [comment]
And now I've officially merged the two branches. Onto the next project!

**Pull request merged**
